FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04

# python package
RUN pip install numpy

RUN pip install h5py

# RUN pip install keras
RUN pip install git+https://github.com/fchollet/keras.git

RUN pip install tensorflow-gpu

# install jupyter
RUN pip install jupyter
