FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
MAINTAINER clliao <runway3611@gmail.com>

# install python 3.6.1 on ubuntu 16.04
# -----------------------------------------------
ENV PATH /usr/local/bin:$PATH
RUN \
    # step 1
    apt-get update && \

    # step 2
    apt-get install build-essential -y && \

    # step 3
    apt-get install wget -y && \

    # step 4
    mkdir open_source && \

    # step 5
    apt-get install python3-dev libffi-dev libssl-dev -y && \

    # step 6
    apt-get install xz-utils -y && \

    # step 7
    apt-get install zlib1g-dev

# Download and install python 3.6.1
# step 8
RUN \
    cd /open_source && \
    wget https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tar.xz && \
    tar xvf Python-3.6.1.tar.xz && \
    cd /open_source/Python-3.6.1/ && \
    ./configure && \
    make altinstall

# linking
# step 9
RUN cd /usr/local/bin && \
    ln -s python3.6 python && \
    ln -s pip3.6 pip
# -----------------------------------------------

